AVAILABILITY_STATUS="Archived"
PROVIDER_STATUS="uploaded"
POSTER_IMAGE_STATUS="File-Created"
RESOURCE_TYPE="Media"

USER_TYPE_VISITOR="Visitor"
USER_TYPE_REGISTERED="Registered"

POSTER_IMAGE_VISITOR_DIRECTORY="public/photos/visitor"
POSTER_IMAGE_REGISTERED_DIRECTORY="public/photos/registered"
